const mensagens = [
    // --- AMOR ---
    "O amor é a força mais sutil do mundo. ❤️", "Amar não é olhar um para o outro, é olhar juntos na mesma direção.", "Você é o meu lugar favorito no mundo.", "Onde há amor, há vida.", "Seu sorriso é o meu motivo para sorrir.", "Cada detalhe seu me faz te querer cada vez mais.", "O amor mora nos pequenos gestos.", "Você é a página mais linda que o destino escreveu na minha vida.", "Amor é quando a felicidade do outro é a sua própria.", "Te amar é a melhor decisão que já tomei.", "O universo conspirou para a gente se encontrar. ✨", "A medida do amor é amar sem medida.", "Você é o meu 'bom dia' favorito.", "Nosso amor é como um jardim: precisa de cuidado e floresce com carinho.", "Amo a forma como você vê o mundo.", "Estar com você é como estar em casa.", "Você é o sonho que eu nunca quis acordar.", "O amor simplifica tudo.", "Nada no mundo é tão doce quanto o seu beijo.", "Você transborda tudo o que eu sempre quis.", "Amar é encontrar a própria felicidade na felicidade do outro.", "Meu coração bate no ritmo do seu.", "Você é a minha melhor metade.", "O amor é o tempero da vida.", "Com você, qualquer lugar é o paraíso.", "Seu abraço é o meu porto seguro.", "Você é o brilho nos meus olhos e a paz no meu coração.", "A vida é muito mais bonita ao seu lado.", "O amor é a única coisa que cresce quando se divide.", "Você é a minha pessoa favorita.", "Amo cada pedacinho de você.", "Juntos somos poesia.", "O amor transforma o comum em extraordinário.", "Você é o meu melhor presente.", "Amar você é tão natural quanto respirar.", "O amor não se explica, se sente.", "Você é o motivo da minha felicidade.", "A vida faz mais sentido com você aqui.", "O nosso amor é a minha maior sorte.", "Você é tudo o que eu sempre procurei.", "Amar é cuidar, respeitar e florescer junto.", "Seu carinho cura qualquer dia ruim.", "Sou louco por cada detalhe seu.", "Você é a melodia da minha música favorita.", "O amor é o elo que nos mantém unidos.", "Meu lugar é onde você estiver.", "Você é a minha paz em meio ao caos.", "Amo o jeito que você me olha.", "Nosso amor é eterno e verdadeiro.", "Você é o grande amor da minha vida. 🌹",

    // --- BÍBLICOS ---
    "Tudo posso naquele que me fortalece. (Filipenses 4:13)", "O Senhor é o meu pastor, nada me faltará. (Salmo 23:1)", "Seja forte e corajoso! Não desanime. (Josué 1:9)", "O choro pode durar uma noite, mas a alegria vem pela manhã. (Salmo 30:5)", "Deus é o nosso refúgio e fortaleza. (Salmo 46:1)", "O Senhor te guardará de todo o mal. (Salmo 121:7)", "O amor nunca falha. (1 Coríntios 13:8)", "A minha graça te basta. (2 Coríntios 12:9)", "Espere no Senhor e seja forte. (Salmo 27:14)", "Deus é amor. (1 João 4:8)", "O Senhor pelejará por vós. (Êxodo 14:14)", "A fé é a certeza daquilo que esperamos. (Hebreus 11:1)", "Confie no Senhor de todo o seu coração. (Provérbios 3:5)", "O Senhor é a minha luz e a minha salvação. (Salmo 27:1)", "Pois eu bem sei os planos que tenho para vós. (Jeremias 29:11)", "Mil cairão ao teu lado, mas tu não serás atingido. (Salmo 91:7)", "Buscai primeiro o Reino de Deus. (Mateus 6:33)", "A alegria do Senhor é a vossa força. (Neemias 8:10)", "Tudo coopera para o bem daqueles que amam a Deus. (Romanos 8:28)", "Não se turbe o vosso coração. (João 14:1)", "O Senhor é bom, um refúgio em tempos de angústia. (Naum 1:7)", "Aquele que habita no esconderijo do Altíssimo descansará. (Salmo 91:1)", "Peçam, e lhes será dado. (Mateus 7:7)", "Se Deus é por nós, quem será contra nós? (Romanos 8:31)", "Lâmpada para os meus pés é tua palavra. (Salmo 119:105)", "A paz de Deus excede todo o entendimento. (Filipenses 4:7)", "Deem graças ao Senhor, porque ele é bom. (Salmo 136:1)", "A vossa fé não se baseia em sabedoria humana. (1 Coríntios 2:5)", "O Senhor é o meu auxílio, não temerei. (Hebreus 13:6)", "O coração alegre afeiçoa o rosto. (Provérbios 15:13)", "Grandes coisas fez o Senhor por nós. (Salmo 126:3)", "Deus é fiel. (1 Coríntios 10:13)", "A oração de um justo é poderosa e eficaz. (Tiago 5:16)", "Não fiquem ansiosos por coisa alguma. (Filipenses 4:6)", "O fruto do Espírito é amor, alegria e paz. (Gálatas 5:22)", "Nada nos separará do amor de Deus. (Romanos 8:39)", "O Senhor sustenta todos os que caem. (Salmo 145:14)", "A palavra do Senhor permanece para sempre. (1 Pedro 1:25)", "Deus supre todas as vossas necessidades. (Filipenses 4:19)", "Clama a mim, e responder-te-ei. (Jeremias 33:3)", "O Senhor está perto dos que têm o coração quebrantado. (Salmo 34:18)", "Sede vós também pacientes e fortalecei os vossos corações. (Tiago 5:8)", "Deus não nos deu espírito de temor, mas de poder. (2 Timóteo 1:7)", "A esperança não nos decepciona. (Romanos 5:5)", "Os que esperam no Senhor renovam as suas forças. (Isaías 40:31)", "Onde está o Espírito do Senhor, aí há liberdade. (2 Coríntios 3:17)", "Toda a boa dádiva vem do alto. (Tiago 1:17)", "Bem-aventurados os pacíficos. (Mateus 5:9)", "Em paz me deito e logo pego no sono. (Salmo 4:8)", "A luz brilha nas trevas. (João 1:5) ✨",

    // --- MOTIVAÇÃO ---
    "Acredite: você é mais forte do que imagina. 💪", "Cada novo dia é uma nova chance de ser feliz.", "Não pare até se orgulhar de você.", "Grandes coisas levam tempo. Tenha paciência.", "Sua única limitação é aquela que você impõe.", "Seja a mudança que você deseja ver no mundo.", "O sucesso é a soma de pequenos esforços repetidos.", "Não deixe que o medo de errar te impeça de jogar.", "A jornada de mil milhas começa com um único passo.", "Transforme seus obstáculos em degraus.", "Foque no progresso, não na perfeição.", "Sua atitude determina sua altitude.", "O melhor ainda está por vir.", "Faça hoje o que o seu 'eu' do futuro vai agradecer.", "O segredo de progredir é começar.", "Seja você mesmo; todos os outros já existem.", "A disciplina é a ponte entre metas e conquistas.", "Lute pelos seus sonhos, mesmo que pareçam distantes.", "Sua luz brilhará se você permitir.", "Hoje é um ótimo dia para começar algo novo.", "Dificuldades preparam pessoas comuns para destinos extraordinários.", "Acreditar é o primeiro passo para realizar.", "A vida retribui o que você oferece.", "Não compare o seu capítulo 1 com o capítulo 20 de outra pessoa.", "Erros são prova de que você está tentando.", "Mantenha o foco e a fé.", "Você é o autor da sua própria história.", "Seja a sua melhor versão hoje.", "Desafios são oportunidades disfarçadas.", "O pensamento positivo atrai coisas positivas.", "Nunca é tarde demais para ser quem você poderia ter sido.", "Persistência é o caminho para o êxito.", "Celebre as suas pequenas vitórias.", "Vá além do que você imagina alcançar.", "O entusiasmo é o combustível da alma.", "Nada é impossível para um coração cheio de vontade.", "Cultive pensamentos bons e colha bons frutos.", "A gratidão transforma o que temos em suficiente.", "Seja resiliente: caia sete vezes, levante-se oito.", "A coragem não é a ausência de medo, mas o triunfo sobre ele.", "Sua mente é sua ferramenta mais poderosa.", "Aproveite cada momento da sua caminhada.", "O sol sempre volta a brilhar após a tempestade.", "Pequenos hábitos mudam vidas.", "Não espere por oportunidades, crie-as.", "Viva intensamente, ame profundamente.", "Você é capaz de superar qualquer desafio.", "Acredite no poder da sua intuição.", "Espalhe bondade por onde passar.", "Amanhã será ainda melhor. Acredite! ☀️"
];

function gerarMensagem() {
    const textoElemento = document.getElementById("mensagem");
    const indiceAleatorio = Math.floor(Math.random() * mensagens.length);
    
    // Efeito de transição suave
    textoElemento.style.opacity = 0;
    
    setTimeout(() => {
        textoElemento.textContent = mensagens[indiceAleatorio];
        textoElemento.style.opacity = 1;
    }, 300);
}

// Inicia com uma mensagem aleatória
window.onload = gerarMensagem;